version: '3.4'

services:
  gripitemtrade.api:
    image: ${DOCKER_REGISTRY-}gripitemtradeapi
    build:
      context: .
      dockerfile: src/GripItemTrade.Api/Dockerfile
  gripitemtrade.sqldb:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "AzureKeyVaultPassword!"
      ACCEPT_EULA: "Y"
  gripitemtrade.infrastructure.tests:
    image: ${DOCKER_REGISTRY-}gripitemtradeinfrastructuretests
    depends_on: 
      - gripitemtrade.sqldb
    build:
      context: .
      dockerfile: tests/GripItemTrade.Infrastructure.Tests/Dockerfile
  gripitemtrade.api.tests:
    image: ${DOCKER_REGISTRY-}gripitemtradeapi
    depends_on: 
      - gripitemtrade.api
    build:
      context: .
      dockerfile: tests/GripItemTrade.Api.Tests/Dockerfile
