version: '3.4'

services:
  gripitemtrade.api:
    image: ${DOCKER_REGISTRY-}gripitemtradeapi
    build:
      context: .
      dockerfile: GripItemTrade.Api/Dockerfile
    depends_on:
      - gripitemtrade.sqldb
  gripitemtrade.sqldb:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "AzureKeyVaultPassword!"
      ACCEPT_EULA: "Y"
